2025-01-15 10:04:45,627 - __mp_main__ - INFO - [multi.py:69] - Environment variables loaded from .env.local
2025-01-15 10:04:45,627 - __mp_main__ - INFO - [multi.py:75] - Environment variable MAIL_DEFAULT_SENDER: [SET]
2025-01-15 10:04:45,627 - __mp_main__ - INFO - [multi.py:75] - Environment variable MAIL_DEFAULT_SENDER_NAME: [SET]
2025-01-15 10:04:45,627 - __mp_main__ - INFO - [multi.py:75] - Environment variable AZURE_OPENAI_ENDPOINT: [SET]
2025-01-15 10:04:45,628 - livekit.agents - INFO - [job_proc_lazy_main.py:72] - initializing job process
2025-01-15 10:04:45,628 - livekit.agents - INFO - [job_proc_lazy_main.py:74] - job process initialized
2025-01-15 10:04:45,629 - asyncio - DEBUG - [selector_events.py:54] - Using selector: KqueueSelector
2025-01-15 10:04:45,631 - __mp_main__ - INFO - [multi.py:48] - ==================================================
2025-01-15 10:04:45,631 - __mp_main__ - INFO - [multi.py:49] - ENTERING FUNCTION: entrypoint
2025-01-15 10:04:45,631 - __mp_main__ - INFO - [multi.py:50] - Arguments: No positional args
2025-01-15 10:04:45,631 - __mp_main__ - INFO - [multi.py:51] - Keyword Arguments: No keyword args
2025-01-15 10:04:45,631 - __mp_main__ - INFO - [multi.py:184] - Starting application entrypoint
2025-01-15 10:04:45,633 - livekit - INFO - [_ffi_client.py:164] - livekit_ffi::server:133:livekit_ffi::server - initializing ffi server v0.12.5
2025-01-15 10:04:45,633 - livekit - INFO - [_ffi_client.py:164] - livekit_ffi::cabi:36:livekit_ffi::cabi - initializing ffi server v0.12.5
2025-01-15 10:04:45,640 - livekit - INFO - [_ffi_client.py:164] - livekit_api::signal_client::signal_stream:96:livekit_api::signal_client::signal_stream - connecting to wss://ai-telecall-w0oao1uz.livekit.cloud/rtc?sdk=python&protocol=15&auto_subscribe=1&adaptive_stream=0&version=0.19.1&access_token=...
2025-01-15 10:04:47,717 - livekit - DEBUG - [_ffi_client.py:164] - rustls::anchors:150:rustls::anchors - add_parsable_certificates processed 153 valid and 0 invalid certs
2025-01-15 10:04:47,717 - livekit - DEBUG - [_ffi_client.py:164] - tokio_tungstenite::tls::encryption::rustls:103:tokio_tungstenite::tls::encryption::rustls - Added 153/153 native root certificates (ignored 0)
2025-01-15 10:04:47,717 - livekit - DEBUG - [_ffi_client.py:164] - rustls::client::hs:73:rustls::client::hs - No cached session for DnsName("ai-telecall-w0oao1uz.livekit.cloud")
2025-01-15 10:04:47,717 - livekit - DEBUG - [_ffi_client.py:164] - rustls::client::hs:132:rustls::client::hs - Not resuming any session
2025-01-15 10:04:48,358 - livekit - DEBUG - [_ffi_client.py:164] - rustls::client::hs:615:rustls::client::hs - Using ciphersuite TLS13_AES_128_GCM_SHA256
2025-01-15 10:04:48,359 - livekit - DEBUG - [_ffi_client.py:164] - rustls::client::tls13:142:rustls::client::tls13 - Not resuming
2025-01-15 10:04:48,359 - livekit - DEBUG - [_ffi_client.py:164] - rustls::client::tls13:381:rustls::client::tls13 - TLS1.3 encrypted extensions: []
2025-01-15 10:04:48,360 - livekit - DEBUG - [_ffi_client.py:164] - rustls::client::hs:472:rustls::client::hs - ALPN protocol is None
2025-01-15 10:04:50,620 - livekit - DEBUG - [_ffi_client.py:164] - tungstenite::handshake::client:95:tungstenite::handshake::client - Client handshake done.
2025-01-15 10:04:52,653 - __mp_main__ - INFO - [multi.py:186] - Connected to room: playground-H3hC-d6Bj
2025-01-15 10:04:52,654 - __mp_main__ - INFO - [multi.py:188] - Initializing chat context
2025-01-15 10:04:52,654 - __mp_main__ - INFO - [multi.py:202] - Initializing Azure GPT
2025-01-15 10:04:52,657 - httpx._config - TRACE - [_utils.py:268] - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-01-15 10:04:52,657 - httpx._config - TRACE - [_utils.py:268] - load_verify_locations cafile=/opt/homebrew/lib/python3.11/site-packages/certifi/cacert.pem
2025-01-15 10:04:52,663 - __mp_main__ - INFO - [multi.py:210] - Initializing Google AI
2025-01-15 10:04:52,688 - httpx._config - TRACE - [_utils.py:268] - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-01-15 10:04:52,689 - httpx._config - TRACE - [_utils.py:268] - load_verify_locations cafile=/opt/homebrew/lib/python3.11/site-packages/certifi/cacert.pem
2025-01-15 10:04:52,771 - __mp_main__ - INFO - [multi.py:215] - Setting up Voice Assistant
2025-01-15 10:04:52,862 - __mp_main__ - INFO - [multi.py:228] - Chat manager initialized
2025-01-15 10:04:52,863 - __mp_main__ - INFO - [multi.py:282] - Starting assistant
2025-01-15 10:04:53,864 - __mp_main__ - INFO - [multi.py:290] - Getting video track
2025-01-15 10:04:53,865 - __mp_main__ - INFO - [multi.py:48] - ==================================================
2025-01-15 10:04:53,865 - __mp_main__ - INFO - [multi.py:49] - ENTERING FUNCTION: get_video_track
2025-01-15 10:04:53,865 - __mp_main__ - INFO - [multi.py:50] - Arguments: No positional args
2025-01-15 10:04:53,865 - __mp_main__ - INFO - [multi.py:51] - Keyword Arguments: No keyword args
2025-01-15 10:04:53,865 - __mp_main__ - INFO - [multi.py:166] - Searching for video track in room: playground-H3hC-d6Bj
2025-01-15 10:04:53,866 - livekit.agents - DEBUG - [http_context.py:20] - http_session(): creating a new httpclient ctx
2025-01-15 10:07:29,413 - livekit - WARNING - [_ffi_client.py:164] - livekit::rtc_engine:436:livekit::rtc_engine - received session close: "signal client closed: \"ping timeout\"" UnknownReason Resume
2025-01-15 10:07:29,415 - livekit - ERROR - [_ffi_client.py:164] - livekit::rtc_engine:692:livekit::rtc_engine - resuming connection... attempt: 0
2025-01-15 10:07:44,051 - livekit.agents - DEBUG - [job_proc_lazy_main.py:254] - shutting down job task
